- id: "1695921607162"
  alias: DS_Cupboard_on
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.ds_cupboard_door_sensor_2_contact
      from: "off"
      to: "on"
  condition: []
  action:
    - type: turn_on
      device_id: e2e7eecbf8de3fc86398848b7ed9b127
      entity_id: b9069a8e4f575b618c2a9893e698d006
      domain: light
  mode: single
- id: "1695921692839"
  alias: DS_Cupboard_off
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.ds_cupboard_door_sensor_2_contact
      from: "on"
      to: "off"
  condition: []
  action:
    - type: turn_off
      device_id: e2e7eecbf8de3fc86398848b7ed9b127
      entity_id: b9069a8e4f575b618c2a9893e698d006
      domain: light
  mode: single
- id: "1695984609406"
  alias: Spare Bedroom Night Scene Button
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_button.spare_bedroom_night_scene
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.spare_room_night_light
      metadata: {}
  mode: single
- id: "1695984991678"
  alias: Turn Off Spare Bedroom Wall Light
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_button.spare_bedroom_lights_off
  condition: []
  action:
    - type: turn_off
      device_id: 54fb76a3d50d007b6058810800250a79
      entity_id: cf8d6e23aec25ce98c166157d26776f1
      domain: light
  mode: single
- id: "1695986742513"
  alias: Brighten Living Room
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_button.living_room_bright
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.living_room_bright
      metadata: {}
  mode: single
- id: "1695986795630"
  alias: Dim Living Room
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_button.living_room_dim
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.living_room_dim
      metadata: {}
  mode: single
- id: "1695986829681"
  alias: TV Lighting
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_button.living_room_tv_lighting
  condition: []
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.living_room_tv_lighting
      metadata: {}
  mode: single
- id: "1695987443667"
  alias: Sunset Lighting
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: "-1:00"
  condition: []
  action:
    - type: turn_on
      device_id: a31cd6d1582876d720d62a96236c3f6b
      entity_id: c4dafb2d48ed6d226aea476c34264c90
      domain: light
      brightness_pct: 60
  mode: single
- id: "1695996225453"
  alias: Porch Light On Before Work
  description: ""
  trigger:
    - platform: time
      at: 05:45:00
  condition:
    - condition: and
      conditions:
        - condition: sun
          before: sunrise
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
  action:
    - type: turn_on
      device_id: 3610e6edf77c064fe0b5a82e218df7a4
      entity_id: 8db3f13f578f5b0bdecfdb7eb175660f
      domain: light
      brightness_pct: 100
  mode: single
- id: "1695996449552"
  alias: Porch Light Off at Sunrise
  description: ""
  trigger:
    - platform: sun
      event: sunrise
      offset: "+1:00"
  condition: []
  action:
    - type: turn_off
      device_id: 3610e6edf77c064fe0b5a82e218df7a4
      entity_id: 8db3f13f578f5b0bdecfdb7eb175660f
      domain: light
  mode: single
- id: "1695996718802"
  alias: Porch Light On At Sunset
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: -00:30:00
  condition: []
  action:
    - type: turn_on
      device_id: 3610e6edf77c064fe0b5a82e218df7a4
      entity_id: 8db3f13f578f5b0bdecfdb7eb175660f
      domain: light
      brightness_pct: 100
  mode: single

- id: "bed_automation"
  alias: Bed Automation
  description: Turns all lights off
  trigger:
    - platform: time
      at: "23:00:00"
    - platform: state
      entity_id:
        - input_button.bed
  condition: []
  action:
    - service: light.turn_off
      target:
        entity_id: all
      data: {}
    - type: turn_off
      device_id: 2dc67447c8ec935a0120525fcae6e28c
      entity_id: 86befecb6ed5d3de829cfd07fcb6a814
      domain: switch
  mode: single

- id: "1696067754529"
  alias: Living Room Lights On In Morning
  description: ""
  trigger:
    - platform: time
      at: 05:40:00
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.morning_lights
      metadata: {}
  mode: single

- id: "1696068091855"
  alias: Morning Lights Off
  description: ""
  trigger:
    - platform: sun
      event: sunrise
      offset: 01:00:00
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
  action:
    - type: turn_off
      device_id: bd7a7f331b0c2f19525b85860f5d6ff6
      entity_id: 036a26770de8d727ebb07e5c3cdcd37f
      domain: light
    - type: turn_off
      device_id: a31cd6d1582876d720d62a96236c3f6b
      entity_id: c4dafb2d48ed6d226aea476c34264c90
      domain: light
  mode: single
