# - id: "bedroom_trv_on_off"
#   alias: Bedroom TRV On / Off
#   description: ""
#   trigger:
#     - platform: state
#       entity_id:
#         - input_boolean.bedroom_trv_open
#       from:
#       to:
#   condition: []
#   action:
#     - choose:
#         - conditions:
#             - condition: state
#               entity_id: input_boolean.bedroom_trv_open
#               state: "on"
#           sequence:
#             - service: climate.set_temperature
#               data:
#                 temperature: 25
#               target:
#                 entity_id: climate.bedroom_trv
#         - conditions:
#             - condition: state
#               entity_id: input_boolean.bedroom_trv_open
#               state: "off"
#           sequence:
#             - service: climate.set_temperature
#               data:
#                 temperature: 5
#               target:
#                 entity_id: climate.bedroom_trv
#   mode: single

- id: "bedroom_auto_temperature_automation"
  alias: Bedroom Auto Temperature Automation
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.bedroom_heating_temp
  condition: []
  action:
    - service: climate.set_temperature
      data:
        temperature: "{{ states('sensor.bedroom_heating_temp') }}"
      target:
        entity_id: climate.bedroom
  mode: single

# Replace these:
#   bedroom_trv_on_off
#   Bedroom TRV On / Off
#   bedroom_trv_open
#   bedroom_trv_sonoff
#
# Opens TRV when commanded by input boolean but only acts if heating is on

# when (input_boolean.bedroom_trv_open ==  new) or (sensor.heating_state == heating)
#   if (sensor.heating_state == heating)
#     if (input_boolean.bedroom_trv_open == on)
#       openTrv()
#     if (input_boolean.bedroom_trv_open == off)
#       closeTrv()()

- id: "bedroom_trv_on_off"
  alias: Bedroom TRV On / Off
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.bedroom_trv_open
    - platform: state
      entity_id:
        - input_boolean.bedroom_trv_monitor_heating
    - platform: state
      entity_id:
        - sensor.heating_state
      from:
      to: heating
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.heating_state
          state: heating
        - condition: state
          entity_id: input_boolean.bedroom_trv_monitor_heating
          state: "off"
  action:
    - if:
        - condition: state
          entity_id: input_boolean.bedroom_trv_open
          state: "on"
      then:
        - service: climate.set_temperature
          target:
            entity_id: climate.bedroom_trv_sonoff
          data:
            temperature: 35
            hvac_mode: heat
    - if:
        - condition: state
          entity_id: input_boolean.bedroom_trv_open
          state: "off"
      then:
        - service: climate.set_temperature
          target:
            entity_id: climate.bedroom_trv_sonoff
          data:
            temperature: 4
            hvac_mode: "off"
  mode: single
