- id: "bedroom_trv_on_off"
  alias: Bedroom TRV On / Off
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.bedroom_trv_open
      from:
      to:
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.bedroom_trv_open
              state: "on"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 25
              target:
                entity_id: climate.bedroom_trv
        - conditions:
            - condition: state
              entity_id: input_boolean.bedroom_trv_open
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 5
              target:
                entity_id: climate.bedroom_trv
  mode: single

- id: 'bedroom_auto_temperature_automation'
  alias: Bedroom Auto Temperature Automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.bedroom_heating_temp
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: "{{states.sensor.bedroom_heating_temp}}"
    target:
      entity_id: climate.bedroom
  mode: single
