- id: "polly_trv_on_off"
  alias: Polly TRV On / Off
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.polly_trv_open
      from:
      to:
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.polly_trv_open
              state: "on"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 22
              target:
                entity_id: climate.polly_trv
        - conditions:
            - condition: state
              entity_id: input_boolean.polly_trv_open
              state: "off"
          sequence:
            - service: climate.set_temperature
              data:
                temperature: 15
              target:
                entity_id: climate.polly_trv
  mode: single