# - id: "polly_trv_on_off"
#   alias: Polly TRV On / Off
#   description: ""
#   trigger:
#     - platform: state
#       entity_id:
#         - input_boolean.polly_trv_open
#       from:
#       to:
#   condition: []
#   action:
#     - choose:
#         - conditions:
#             - condition: state
#               entity_id: input_boolean.polly_trv_open
#               state: "on"
#           sequence:
#             - service: climate.set_temperature
#               data:
#                 temperature: 22
#               target:
#                 entity_id: climate.polly_trv
#         - conditions:
#             - condition: state
#               entity_id: input_boolean.polly_trv_open
#               state: "off"
#           sequence:
#             - service: climate.set_temperature
#               data:
#                 temperature: 15
#               target:
#                 entity_id: climate.polly_trv
#   mode: single

- id: "polly_auto_temperature_automation"
  alias: Polly Auto Temperature Automation
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.polly_heating_temp
  condition: []
  action:
    - service: climate.set_temperature
      data:
        temperature: "{{ states('sensor.polly_heating_temp') }}"
      target:
        entity_id: climate.polly
  mode: single

- id: "polly_trv_on_off"
  alias: Polly TRV On / Off
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.polly_trv_open
  condition: []
  action:
    - if:
        - condition: state
          entity_id: input_boolean.polly_trv_open
          state: "on"
      then:
        - service: climate.set_temperature
          target:
            device_id: e7e343b474074f82fe8cb569a08553f9
          data:
            temperature: 35
            hvac_mode: heat
      else:
        - service: climate.set_temperature
          target:
            device_id: e7e343b474074f82fe8cb569a08553f9
          data:
            temperature: 35
            hvac_mode: "off"
  mode: single
