- id: "polly_bedtime_music"
  alias: Polly bedtime music
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.tuya_motion_3_occupancy
      to: "on"
    # - platform: state
    #   entity_id:
    #     - schedule.polly_music_schedule
    #   to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.enable_polly_music
      state: "on"
    - condition: state
      entity_id: schedule.polly_music_schedule
      state: "on"
  action:
    - service: media_player.volume_set
      target:
        entity_id: media_player.living_room_speaker
      data:
        volume_level: 0.15
    - repeat:
        sequence:
          - service: media_player.play_media
            target:
              entity_id: media_player.living_room_speaker
            data:
              #media_content_id: media-source://media_source/local/enyaShort.mp3
              media_content_id: media-source://media_source/local/04 - Caribbean Blue.mp3
              #media_content_id: media-source://media_source/local/lanterns1.mp3
              media_content_type: audio/mpeg
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - wait_for_trigger:
              - platform: state
                entity_id:
                  - media_player.living_room_speaker
                from: playing
                to: idle
            continue_on_timeout: false
          # - service: media_player.play_media
          #   target:
          #     entity_id: media_player.living_room_speaker
          #   data:
          #     #media_content_id: media-source://media_source/local/enyaShort.mp3
          #     # media_content_id: media-source://media_source/local/04 - Caribbean Blue.mp3
          #     media_content_id: media-source://media_source/local/lanterns2.mp3
          #     media_content_type: audio/mpeg
          # - delay:
          #     hours: 0
          #     minutes: 0
          #     seconds: 2
          #     milliseconds: 0
          # - wait_for_trigger:
          #   - platform: state
          #     entity_id:
          #     - media_player.living_room_speaker
          #     from: playing
          #     to: idle
          #   continue_on_timeout: false
          # - service: media_player.play_media
          #   target:
          #     entity_id: media_player.living_room_speaker
          #   data:
          #     #media_content_id: media-source://media_source/local/enyaShort.mp3
          #     # media_content_id: media-source://media_source/local/04 - Caribbean Blue.mp3
          #     media_content_id: media-source://media_source/local/lanterns3.mp3
          #     media_content_type: audio/mpeg
          # - delay:
          #     hours: 0
          #     minutes: 0
          #     seconds: 2
          #     milliseconds: 0
          # - wait_for_trigger:
          #   - platform: state
          #     entity_id:
          #     - media_player.living_room_speaker
          #     from: playing
          #     to: idle
          #   continue_on_timeout: false
        until:
          - condition: or
            conditions:
              - condition: state
                entity_id: schedule.polly_music_schedule
                state: "off"
              - condition: state
                entity_id: input_boolean.enable_polly_music
                state: "off"
  mode: single

- id: "stop_polly_music"
  alias: Stop Polly Music
  description: ""
  trigger: []
  condition: []
  action:
    - service: automation.turn_off
      target:
        entity_id: automation.polly_bedtime_music_2
      data:
        stop_actions: true
    - service: media_player.media_stop
      target:
        entity_id: media_player.living_room_speaker
      data: {}
    - service: automation.turn_on
      target:
        entity_id: automation.polly_bedtime_music_2
      data: {}
  mode: single
