# Replace these:
#   spare_bedroom_trv_on_off
#   Spare Bedroom TRV On / Off
#   spare_bedroom_trv_open
#   spare_bedroom_trv_sonoff
#
# Opens TRV when commanded by input boolean but only acts if heating is on

# when (input_boolean.spare_bedroom_trv_open ==  new) or (sensor.heating_state == heating)
#   if (sensor.heating_state == heating)
#     if (input_boolean.spare_bedroom_trv_open == on)
#       openTrv()
#     if (input_boolean.spare_bedroom_trv_open == off)
#       closeTrv()()

- id: "spare_bedroom_trv_on_off"
  alias: Spare Bedroom TRV On / Off
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.spare_bedroom_trv_open
    - platform: state
      entity_id:
        - input_boolean.spare_bedroom_trv_monitor_heating
    - platform: state
      entity_id:
        - sensor.heating_state
      from:
      to: heating
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.heating_state
          state: heating
        - condition: state
          entity_id: input_boolean.spare_bedroom_trv_monitor_heating
          state: "off"
  action:
    - if:
        - condition: state
          entity_id: input_boolean.spare_bedroom_trv_open
          state: "on"
      then:
        - service: climate.set_temperature
          target:
            entity_id: climate.spare_bedroom_trv_sonoff
          data:
            temperature: 35
            hvac_mode: heat
    - if:
        - condition: state
          entity_id: input_boolean.spare_bedroom_trv_open
          state: "off"
      then:
        - service: climate.set_temperature
          target:
            entity_id: climate.spare_bedroom_trv_sonoff
          data:
            temperature: 4
            hvac_mode: "off"
  mode: single
