# Custom sensor describing the setpoint temperature of the central heating
# for the current time
- platform: template
  sensors:
    lees_phone_next_alarm:
      value_template: >
        {{ state_attr('sensor.pixel_8_next_alarm','Local Time').split()[3]}}
    alarm_is_today:
      value_template: >
        {% if state_attr('sensor.pixel_8_next_alarm','Local Time').split()[2] | int == now().day %}
        True
        {% else %}
        False
        {% endif %}
