# Custom sensor describing the setpoint temperature of the central heating
# for the current time
- platform: template
  sensors:
    polly_heating_temp:
      value_template: >
        {% if (now().hour < 8) %}
          18
        {% elif (now().hour >= 8) and (now().hour < 18) %}
          19
        {% elif (now().hour >= 18) %}
          18
        {% endif %}
