# Custom sensor describing the setpoint temperature of the central heating
# for the current time
- platform: template
  sensors:
    spare_bedroom_heating_temp:
      value_template: >
        {% if (now().hour < 8) %}
          18
        {% elif (now().hour >= 8) and (now().hour < 20) %}
          21
        {% elif (now().hour >= 20) %}
          18
        {% endif %}
    spare_bedroom_boost_temp:
      value_template: >
        {{ state_attr('climate.spare_bedroom','current_temperature') |float + 1 | float }}
    spare_bedroom_valve_dmd:
      value_template: >
        {% set valve_command = states('input_boolean.spare_bedroom_trv_open') %}
        {% if valve_command == 'on' %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >
        {% set valve_command = states('input_boolean.spare_bedroom_trv_open') %}
        {% if valve_command == 'on' %}
          mdi:valve-open
        {% else %}
          mdi:valve-closed
        {% endif %}
    spare_bedroom_valve_rbv:
      value_template: >
        {% set valve_rbv = state_attr('climate.spare_bedroom_trv_sonoff','hvac_action') %}
        {% if valve_rbv == 'off' %}
          Closed
        {% else %}
          Open
        {% endif %}
      icon_template: >
        {% set valve_rbv = state_attr('climate.spare_bedroom_trv_sonoff','hvac_action') %}
        {% if valve_rbv == 'off' %}
          mdi:valve-closed
        {% else %}
          mdi:valve-open
        {% endif %}

